Replace set socket option function
sysprog21/khttpd pull request #5
Opened 2021-05-29 15:58 UTC by bakudr18

kernel_setsockopt was removed since Linux v5.8 which is the Ubuntu 
20.04.2 LTS default version.
Note that in Linux v5.8, sock_setsockopt only accept user space val as
argument. There is no good method to set sndbuf without changing kernel
source.

2021-05-29 16:11 UTC, jserv requested changes
You have to take backwards compatibility into consideration. That is, you have to ensure `khttpd` buildable and runnable for Linux v5.4+ (Ubuntu Linux 20.04-LTS is assumed). Use the following carefully:
```c
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5.8.0)
...
#else
...
#endif
```

2021-05-29 16:42 UTC, bakudr18 commented
Add kernel version check for better compatibility.
Please check!

2021-05-29 16:47 UTC, jserv commented
For reference
- Linux v2.6.19 introduced kernel_setsockopt
- Linux v5.8 removed `kernel_setsockopt` and replaced the functionality with a set of new functions (`ip_sock_set_*`)

2021-05-29 16:48 UTC, jserv requested changes
Create wrapper functions that replace the kernel_setsockopt calls with calls to the appropriate Linux kernel function(s) (depending on what functions the kernel supports). Thus, you can minimize the necessary changes.

2021-05-30 04:14 UTC, bakudr18 commented
> For reference
> 
> * Linux v2.6.19 introduced kernel_setsockopt
> * Linux v5.8 removed `kernel_setsockopt` and replaced the functionality with a set of new functions (`ip_sock_set_*`)

I didn't catch the point of `ip_sock_set_*`
I only found these function in Linux v5.8.0 `include/net/ip.h`, but it's not for replacing `kernel_setsockopt`
```
void ip_sock_set_freebind(struct sock *sk);
int ip_sock_set_mtu_discover(struct sock *sk, int val);
void ip_sock_set_pktinfo(struct sock *sk);
void ip_sock_set_recverr(struct sock *sk);
void ip_sock_set_tos(struct sock *sk, int val);
```

2021-05-30 04:24 UTC, jserv commented on main.c
> +static int _sock_setsockopt(struct socket *sock,
Simply name it `set_sockopt`.

2021-05-30 04:26 UTC, jserv commented on main.c
> +static int _tcp_setsockopt(struct socket *sock,
Ditto. Name it `set_tcp_opt`.

2021-05-30 04:27 UTC, jserv commented on main.c
> +    else
Remove this `else` statement since it is redundant.

2021-05-30 04:52 UTC, bakudr18 commented
Done.
Thanks for these advises.
Please check!

2021-05-30 04:55 UTC, jserv commented
> Done.
> Thanks for these advises.
> Please check!

Next time, you don't have to leave the above message. Instead, you can click the button to request review.
<img width="308" alt="截圖 2021-05-30 下午12 53 11" src="https://user-images.githubusercontent.com/478921/120092527-1cccfe00-c146-11eb-8823-f2f22de4c243.png">

2021-05-30 04:57 UTC, merged